import React, { useMemo } from "react";
import { Chart } from "react-google-charts";

// ---------------------------------------------------------------------
// Country name -> ISO 3166-1 alpha-2 code lookup.
//
// Google's GeoChart only lights up a region when it recognizes the exact
// name (or code) it was given. A study's "Country" field is free text, so
// people naturally type all sorts of things for the same country --
// "USA", "US", "United States", "U.S.A.", "america" -- and GeoChart does
// NOT understand most of those on its own. Anything it doesn't recognize
// gets silently dropped (no error, it just never appears on the map),
// which is why sites logged as "USA", "Aus", or "England" were missing
// while "germany" showed up fine.
//
// The fix: normalize every country string to its ISO alpha-2 code before
// handing it to GeoChart. GeoChart resolves alpha-2 codes unambiguously
// regardless of naming convention, so this covers every country in the
// world, not just a hand-picked few. COUNTRY_ALIASES below is generated
// from the full ISO-3166-1 country list (all 249 official names, alpha-2
// and alpha-3 codes) plus everyday nicknames/abbreviations layered on
// top (USA, UK, Aus, UAE, Holland, Burma, DRC, etc.). Any country name,
// code, or common nickname typed into a study's Country field anywhere
// in the world will resolve correctly here.
const COUNTRY_ALIASES = {
  "abw": "AW",
  "ad": "AD",
  "ae": "AE",
  "af": "AF",
  "afg": "AF",
  "afghanistan": "AF",
  "ag": "AG",
  "ago": "AO",
  "ai": "AI",
  "aia": "AI",
  "al": "AL",
  "ala": "AX",
  "alb": "AL",
  "albania": "AL",
  "algeria": "DZ",
  "am": "AM",
  "america": "US",
  "american samoa": "AS",
  "and": "AD",
  "andorra": "AD",
  "angola": "AO",
  "anguilla": "AI",
  "antarctica": "AQ",
  "antigua and barbuda": "AG",
  "ao": "AO",
  "aq": "AQ",
  "ar": "AR",
  "are": "AE",
  "arg": "AR",
  "argentina": "AR",
  "arm": "AM",
  "armenia": "AM",
  "aruba": "AW",
  "as": "AS",
  "asm": "AS",
  "at": "AT",
  "ata": "AQ",
  "atf": "TF",
  "atg": "AG",
  "au": "AU",
  "aus": "AU",
  "australia": "AU",
  "austria": "AT",
  "aut": "AT",
  "aw": "AW",
  "ax": "AX",
  "az": "AZ",
  "aze": "AZ",
  "azerbaijan": "AZ",
  "ba": "BA",
  "bahamas": "BS",
  "bahrain": "BH",
  "bangladesh": "BD",
  "barbados": "BB",
  "bb": "BB",
  "bd": "BD",
  "bdi": "BI",
  "be": "BE",
  "bel": "BE",
  "belarus": "BY",
  "belgium": "BE",
  "belize": "BZ",
  "ben": "BJ",
  "benin": "BJ",
  "bermuda": "BM",
  "bes": "BQ",
  "bf": "BF",
  "bfa": "BF",
  "bg": "BG",
  "bgd": "BD",
  "bgr": "BG",
  "bh": "BH",
  "bhr": "BH",
  "bhs": "BS",
  "bhutan": "BT",
  "bi": "BI",
  "bih": "BA",
  "bj": "BJ",
  "bl": "BL",
  "blm": "BL",
  "blr": "BY",
  "blz": "BZ",
  "bm": "BM",
  "bmu": "BM",
  "bn": "BN",
  "bo": "BO",
  "bol": "BO",
  "bolivia": "BO",
  "bolivia, plurinational state of": "BO",
  "bonaire, sint eustatius and saba": "BQ",
  "bosnia and herzegovina": "BA",
  "botswana": "BW",
  "bouvet island": "BV",
  "bq": "BQ",
  "br": "BR",
  "bra": "BR",
  "brazil": "BR",
  "brb": "BB",
  "britain": "GB",
  "british indian ocean territory": "IO",
  "british virgin islands": "VG",
  "brn": "BN",
  "brunei": "BN",
  "brunei darussalam": "BN",
  "bs": "BS",
  "bt": "BT",
  "btn": "BT",
  "bulgaria": "BG",
  "burkina faso": "BF",
  "burma": "MM",
  "burundi": "BI",
  "bv": "BV",
  "bvt": "BV",
  "bw": "BW",
  "bwa": "BW",
  "by": "BY",
  "bz": "BZ",
  "ca": "CA",
  "cabo verde": "CV",
  "caf": "CF",
  "cambodia": "KH",
  "cameroon": "CM",
  "can": "CA",
  "canada": "CA",
  "cape verde": "CV",
  "cayman islands": "KY",
  "cc": "CC",
  "cck": "CC",
  "cd": "CD",
  "central african republic": "CF",
  "cf": "CF",
  "cg": "CG",
  "ch": "CH",
  "chad": "TD",
  "che": "CH",
  "chile": "CL",
  "china": "CN",
  "chinese taipei": "TW",
  "chl": "CL",
  "chn": "CN",
  "christmas island": "CX",
  "ci": "CI",
  "civ": "CI",
  "ck": "CK",
  "cl": "CL",
  "cm": "CM",
  "cmr": "CM",
  "cn": "CN",
  "co": "CO",
  "cocos (keeling) islands": "CC",
  "cod": "CD",
  "cog": "CG",
  "cok": "CK",
  "col": "CO",
  "colombia": "CO",
  "com": "KM",
  "comoros": "KM",
  "congo": "CG",
  "congo, democratic republic of the": "CD",
  "congo-brazzaville": "CG",
  "congo-kinshasa": "CD",
  "cook islands": "CK",
  "costa rica": "CR",
  "cpv": "CV",
  "cr": "CR",
  "cri": "CR",
  "croatia": "HR",
  "cu": "CU",
  "cub": "CU",
  "cuba": "CU",
  "curaçao": "CW",
  "cuw": "CW",
  "cv": "CV",
  "cw": "CW",
  "cx": "CX",
  "cxr": "CX",
  "cy": "CY",
  "cym": "KY",
  "cyp": "CY",
  "cyprus": "CY",
  "cz": "CZ",
  "cze": "CZ",
  "czech republic": "CZ",
  "czechia": "CZ",
  "côte d'ivoire": "CI",
  "de": "DE",
  "democratic republic of congo": "CD",
  "democratic republic of the congo": "CD",
  "denmark": "DK",
  "deu": "DE",
  "dj": "DJ",
  "dji": "DJ",
  "djibouti": "DJ",
  "dk": "DK",
  "dm": "DM",
  "dma": "DM",
  "dnk": "DK",
  "do": "DO",
  "dom": "DO",
  "dominica": "DM",
  "dominican republic": "DO",
  "dr congo": "CD",
  "drc": "CD",
  "dz": "DZ",
  "dza": "DZ",
  "east timor": "TL",
  "ec": "EC",
  "ecu": "EC",
  "ecuador": "EC",
  "ee": "EE",
  "eg": "EG",
  "egy": "EG",
  "egypt": "EG",
  "eh": "EH",
  "el salvador": "SV",
  "england": "GB",
  "equatorial guinea": "GQ",
  "er": "ER",
  "eri": "ER",
  "eritrea": "ER",
  "es": "ES",
  "esh": "EH",
  "esp": "ES",
  "est": "EE",
  "estonia": "EE",
  "eswatini": "SZ",
  "et": "ET",
  "eth": "ET",
  "ethiopia": "ET",
  "falkland islands (malvinas)": "FK",
  "faroe islands": "FO",
  "fi": "FI",
  "fiji": "FJ",
  "fin": "FI",
  "finland": "FI",
  "fj": "FJ",
  "fji": "FJ",
  "fk": "FK",
  "flk": "FK",
  "fm": "FM",
  "fo": "FO",
  "fr": "FR",
  "fra": "FR",
  "france": "FR",
  "french guiana": "GF",
  "french polynesia": "PF",
  "french southern territories": "TF",
  "fro": "FO",
  "fsm": "FM",
  "ga": "GA",
  "gab": "GA",
  "gabon": "GA",
  "gambia": "GM",
  "gb": "GB",
  "gbr": "GB",
  "gd": "GD",
  "ge": "GE",
  "geo": "GE",
  "georgia": "GE",
  "germany": "DE",
  "gf": "GF",
  "gg": "GG",
  "ggy": "GG",
  "gh": "GH",
  "gha": "GH",
  "ghana": "GH",
  "gi": "GI",
  "gib": "GI",
  "gibraltar": "GI",
  "gin": "GN",
  "gl": "GL",
  "glp": "GP",
  "gm": "GM",
  "gmb": "GM",
  "gn": "GN",
  "gnb": "GW",
  "gnq": "GQ",
  "gp": "GP",
  "gq": "GQ",
  "gr": "GR",
  "grc": "GR",
  "grd": "GD",
  "great britain": "GB",
  "greece": "GR",
  "greenland": "GL",
  "grenada": "GD",
  "grl": "GL",
  "gs": "GS",
  "gt": "GT",
  "gtm": "GT",
  "gu": "GU",
  "guadeloupe": "GP",
  "guam": "GU",
  "guatemala": "GT",
  "guernsey": "GG",
  "guf": "GF",
  "guinea": "GN",
  "guinea-bissau": "GW",
  "gum": "GU",
  "guy": "GY",
  "guyana": "GY",
  "gw": "GW",
  "gy": "GY",
  "haiti": "HT",
  "heard island and mcdonald islands": "HM",
  "hk": "HK",
  "hkg": "HK",
  "hm": "HM",
  "hmd": "HM",
  "hn": "HN",
  "hnd": "HN",
  "holland": "NL",
  "holy see": "VA",
  "honduras": "HN",
  "hong kong": "HK",
  "hr": "HR",
  "hrv": "HR",
  "ht": "HT",
  "hti": "HT",
  "hu": "HU",
  "hun": "HU",
  "hungary": "HU",
  "iceland": "IS",
  "id": "ID",
  "idn": "ID",
  "ie": "IE",
  "il": "IL",
  "im": "IM",
  "imn": "IM",
  "in": "IN",
  "ind": "IN",
  "india": "IN",
  "indonesia": "ID",
  "io": "IO",
  "iot": "IO",
  "iq": "IQ",
  "ir": "IR",
  "iran": "IR",
  "iran, islamic republic of": "IR",
  "iraq": "IQ",
  "ireland": "IE",
  "irl": "IE",
  "irn": "IR",
  "irq": "IQ",
  "is": "IS",
  "isl": "IS",
  "isle of man": "IM",
  "isr": "IL",
  "israel": "IL",
  "it": "IT",
  "ita": "IT",
  "italy": "IT",
  "ivory coast": "CI",
  "jam": "JM",
  "jamaica": "JM",
  "japan": "JP",
  "je": "JE",
  "jersey": "JE",
  "jey": "JE",
  "jm": "JM",
  "jo": "JO",
  "jor": "JO",
  "jordan": "JO",
  "jp": "JP",
  "jpn": "JP",
  "kaz": "KZ",
  "kazakhstan": "KZ",
  "ke": "KE",
  "ken": "KE",
  "kenya": "KE",
  "kg": "KG",
  "kgz": "KG",
  "kh": "KH",
  "khm": "KH",
  "ki": "KI",
  "kir": "KI",
  "kiribati": "KI",
  "kiwi": "NZ",
  "km": "KM",
  "kn": "KN",
  "kna": "KN",
  "kor": "KR",
  "korea": "KR",
  "korea, democratic people's republic of": "KP",
  "korea, republic of": "KR",
  "kp": "KP",
  "kr": "KR",
  "ksa": "SA",
  "kuwait": "KW",
  "kw": "KW",
  "kwt": "KW",
  "ky": "KY",
  "kyrgyzstan": "KG",
  "kz": "KZ",
  "la": "LA",
  "lao": "LA",
  "lao people's democratic republic": "LA",
  "laos": "LA",
  "latvia": "LV",
  "lb": "LB",
  "lbn": "LB",
  "lbr": "LR",
  "lby": "LY",
  "lc": "LC",
  "lca": "LC",
  "lebanon": "LB",
  "lesotho": "LS",
  "li": "LI",
  "liberia": "LR",
  "libya": "LY",
  "lie": "LI",
  "liechtenstein": "LI",
  "lithuania": "LT",
  "lk": "LK",
  "lka": "LK",
  "lr": "LR",
  "ls": "LS",
  "lso": "LS",
  "lt": "LT",
  "ltu": "LT",
  "lu": "LU",
  "lux": "LU",
  "luxembourg": "LU",
  "lv": "LV",
  "lva": "LV",
  "ly": "LY",
  "ma": "MA",
  "mac": "MO",
  "macao": "MO",
  "macedonia": "MK",
  "madagascar": "MG",
  "maf": "MF",
  "mainland china": "CN",
  "malawi": "MW",
  "malaysia": "MY",
  "maldives": "MV",
  "mali": "ML",
  "malta": "MT",
  "mar": "MA",
  "marshall islands": "MH",
  "martinique": "MQ",
  "mauritania": "MR",
  "mauritius": "MU",
  "mayotte": "YT",
  "mc": "MC",
  "mco": "MC",
  "md": "MD",
  "mda": "MD",
  "mdg": "MG",
  "mdv": "MV",
  "me": "ME",
  "mex": "MX",
  "mexico": "MX",
  "mf": "MF",
  "mg": "MG",
  "mh": "MH",
  "mhl": "MH",
  "micronesia": "FM",
  "micronesia, federated states of": "FM",
  "mk": "MK",
  "mkd": "MK",
  "ml": "ML",
  "mli": "ML",
  "mlt": "MT",
  "mm": "MM",
  "mmr": "MM",
  "mn": "MN",
  "mne": "ME",
  "mng": "MN",
  "mnp": "MP",
  "mo": "MO",
  "moldova": "MD",
  "moldova, republic of": "MD",
  "monaco": "MC",
  "mongolia": "MN",
  "montenegro": "ME",
  "montserrat": "MS",
  "morocco": "MA",
  "moz": "MZ",
  "mozambique": "MZ",
  "mp": "MP",
  "mq": "MQ",
  "mr": "MR",
  "mrt": "MR",
  "ms": "MS",
  "msr": "MS",
  "mt": "MT",
  "mtq": "MQ",
  "mu": "MU",
  "mus": "MU",
  "mv": "MV",
  "mw": "MW",
  "mwi": "MW",
  "mx": "MX",
  "my": "MY",
  "myanmar": "MM",
  "mys": "MY",
  "myt": "YT",
  "mz": "MZ",
  "na": "NA",
  "nam": "NA",
  "namibia": "NA",
  "nauru": "NR",
  "nc": "NC",
  "ncl": "NC",
  "ne": "NE",
  "nepal": "NP",
  "ner": "NE",
  "netherlands": "NL",
  "netherlands, kingdom of the": "NL",
  "new caledonia": "NC",
  "new zealand": "NZ",
  "nf": "NF",
  "nfk": "NF",
  "ng": "NG",
  "nga": "NG",
  "ni": "NI",
  "nic": "NI",
  "nicaragua": "NI",
  "niger": "NE",
  "nigeria": "NG",
  "niu": "NU",
  "niue": "NU",
  "nl": "NL",
  "nld": "NL",
  "no": "NO",
  "nor": "NO",
  "norfolk island": "NF",
  "north korea": "KP",
  "north macedonia": "MK",
  "northern ireland": "GB",
  "northern mariana islands": "MP",
  "norway": "NO",
  "np": "NP",
  "npl": "NP",
  "nr": "NR",
  "nru": "NR",
  "nu": "NU",
  "nz": "NZ",
  "nzl": "NZ",
  "om": "OM",
  "oman": "OM",
  "omn": "OM",
  "pa": "PA",
  "pak": "PK",
  "pakistan": "PK",
  "palau": "PW",
  "palestine": "PS",
  "palestine, state of": "PS",
  "pan": "PA",
  "panama": "PA",
  "papua new guinea": "PG",
  "paraguay": "PY",
  "pcn": "PN",
  "pe": "PE",
  "per": "PE",
  "peru": "PE",
  "pf": "PF",
  "pg": "PG",
  "ph": "PH",
  "philippines": "PH",
  "phl": "PH",
  "pitcairn": "PN",
  "pk": "PK",
  "pl": "PL",
  "plw": "PW",
  "pm": "PM",
  "pn": "PN",
  "png": "PG",
  "pol": "PL",
  "poland": "PL",
  "portugal": "PT",
  "pr": "PR",
  "prc": "CN",
  "pri": "PR",
  "prk": "KP",
  "prt": "PT",
  "pry": "PY",
  "ps": "PS",
  "pse": "PS",
  "pt": "PT",
  "puerto rico": "PR",
  "pw": "PW",
  "py": "PY",
  "pyf": "PF",
  "qa": "QA",
  "qat": "QA",
  "qatar": "QA",
  "re": "RE",
  "republic of congo": "CG",
  "republic of korea": "KR",
  "republic of the congo": "CG",
  "reu": "RE",
  "ro": "RO",
  "roc": "TW",
  "romania": "RO",
  "rou": "RO",
  "rs": "RS",
  "ru": "RU",
  "rus": "RU",
  "russia": "RU",
  "russian federation": "RU",
  "rw": "RW",
  "rwa": "RW",
  "rwanda": "RW",
  "réunion": "RE",
  "sa": "SA",
  "saint barthélemy": "BL",
  "saint helena, ascension and tristan da cunha": "SH",
  "saint kitts and nevis": "KN",
  "saint lucia": "LC",
  "saint martin (french part)": "MF",
  "saint pierre and miquelon": "PM",
  "saint vincent and the grenadines": "VC",
  "samoa": "WS",
  "san marino": "SM",
  "sao tome and principe": "ST",
  "sau": "SA",
  "saudi": "SA",
  "saudi arabia": "SA",
  "sb": "SB",
  "sc": "SC",
  "scotland": "GB",
  "sd": "SD",
  "sdn": "SD",
  "se": "SE",
  "sen": "SN",
  "senegal": "SN",
  "serbia": "RS",
  "seychelles": "SC",
  "sg": "SG",
  "sgp": "SG",
  "sgs": "GS",
  "sh": "SH",
  "shn": "SH",
  "si": "SI",
  "sierra leone": "SL",
  "singapore": "SG",
  "sint maarten (dutch part)": "SX",
  "sj": "SJ",
  "sjm": "SJ",
  "sk": "SK",
  "sl": "SL",
  "slb": "SB",
  "sle": "SL",
  "slovakia": "SK",
  "slovenia": "SI",
  "slv": "SV",
  "sm": "SM",
  "smr": "SM",
  "sn": "SN",
  "so": "SO",
  "solomon islands": "SB",
  "som": "SO",
  "somalia": "SO",
  "south africa": "ZA",
  "south georgia and the south sandwich islands": "GS",
  "south korea": "KR",
  "south sudan": "SS",
  "spain": "ES",
  "spm": "PM",
  "sr": "SR",
  "srb": "RS",
  "sri lanka": "LK",
  "ss": "SS",
  "ssd": "SS",
  "st": "ST",
  "stp": "ST",
  "sudan": "SD",
  "sur": "SR",
  "suriname": "SR",
  "sv": "SV",
  "svalbard and jan mayen": "SJ",
  "svk": "SK",
  "svn": "SI",
  "swaziland": "SZ",
  "swe": "SE",
  "sweden": "SE",
  "switzerland": "CH",
  "swz": "SZ",
  "sx": "SX",
  "sxm": "SX",
  "sy": "SY",
  "syc": "SC",
  "syr": "SY",
  "syria": "SY",
  "syrian arab republic": "SY",
  "sz": "SZ",
  "taiwan": "TW",
  "taiwan, province of china": "TW",
  "tajikistan": "TJ",
  "tanzania": "TZ",
  "tanzania, united republic of": "TZ",
  "tc": "TC",
  "tca": "TC",
  "tcd": "TD",
  "td": "TD",
  "tf": "TF",
  "tg": "TG",
  "tgo": "TG",
  "th": "TH",
  "tha": "TH",
  "thailand": "TH",
  "timor-leste": "TL",
  "tj": "TJ",
  "tjk": "TJ",
  "tk": "TK",
  "tkl": "TK",
  "tkm": "TM",
  "tl": "TL",
  "tls": "TL",
  "tm": "TM",
  "tn": "TN",
  "to": "TO",
  "togo": "TG",
  "tokelau": "TK",
  "ton": "TO",
  "tonga": "TO",
  "tr": "TR",
  "trinidad and tobago": "TT",
  "tt": "TT",
  "tto": "TT",
  "tun": "TN",
  "tunisia": "TN",
  "tur": "TR",
  "turkey": "TR",
  "turkmenistan": "TM",
  "turks and caicos islands": "TC",
  "tuv": "TV",
  "tuvalu": "TV",
  "tv": "TV",
  "tw": "TW",
  "twn": "TW",
  "tz": "TZ",
  "tza": "TZ",
  "türkiye": "TR",
  "u.a.e.": "AE",
  "u.k.": "GB",
  "u.s.": "US",
  "u.s. virgin islands": "VI",
  "u.s.a.": "US",
  "ua": "UA",
  "uae": "AE",
  "ug": "UG",
  "uga": "UG",
  "uganda": "UG",
  "uk": "GB",
  "ukr": "UA",
  "ukraine": "UA",
  "um": "UM",
  "umi": "UM",
  "united arab emirates": "AE",
  "united kingdom": "GB",
  "united kingdom of great britain and northern ireland": "GB",
  "united states": "US",
  "united states minor outlying islands": "UM",
  "united states of america": "US",
  "uruguay": "UY",
  "ury": "UY",
  "us": "US",
  "usa": "US",
  "uy": "UY",
  "uz": "UZ",
  "uzb": "UZ",
  "uzbekistan": "UZ",
  "va": "VA",
  "vanuatu": "VU",
  "vat": "VA",
  "vatican city": "VA",
  "vc": "VC",
  "vct": "VC",
  "ve": "VE",
  "ven": "VE",
  "venezuela": "VE",
  "venezuela, bolivarian republic of": "VE",
  "vg": "VG",
  "vgb": "VG",
  "vi": "VI",
  "viet nam": "VN",
  "vietnam": "VN",
  "vir": "VI",
  "virgin islands (british)": "VG",
  "virgin islands (u.s.)": "VI",
  "vn": "VN",
  "vnm": "VN",
  "vu": "VU",
  "vut": "VU",
  "wales": "GB",
  "wallis and futuna": "WF",
  "western sahara": "EH",
  "wf": "WF",
  "wlf": "WF",
  "ws": "WS",
  "wsm": "WS",
  "ye": "YE",
  "yem": "YE",
  "yemen": "YE",
  "yt": "YT",
  "za": "ZA",
  "zaf": "ZA",
  "zambia": "ZM",
  "zimbabwe": "ZW",
  "zm": "ZM",
  "zmb": "ZM",
  "zw": "ZW",
  "zwe": "ZW",
  "åland islands": "AX"
};

// alpha-2 -> the common English display name, used for on-screen labels
// (e.g. the "couldn't recognize" notice) -- GeoChart resolves its own
// tooltip labels from the code, this is just for our own UI text.
const ALPHA2_TO_NAME = {
  "AD": "Andorra",
  "AE": "United Arab Emirates",
  "AF": "Afghanistan",
  "AG": "Antigua and Barbuda",
  "AI": "Anguilla",
  "AL": "Albania",
  "AM": "Armenia",
  "AO": "Angola",
  "AQ": "Antarctica",
  "AR": "Argentina",
  "AS": "American Samoa",
  "AT": "Austria",
  "AU": "Australia",
  "AW": "Aruba",
  "AX": "Åland Islands",
  "AZ": "Azerbaijan",
  "BA": "Bosnia and Herzegovina",
  "BB": "Barbados",
  "BD": "Bangladesh",
  "BE": "Belgium",
  "BF": "Burkina Faso",
  "BG": "Bulgaria",
  "BH": "Bahrain",
  "BI": "Burundi",
  "BJ": "Benin",
  "BL": "Saint Barthélemy",
  "BM": "Bermuda",
  "BN": "Brunei",
  "BO": "Bolivia",
  "BQ": "Bonaire, Sint Eustatius and Saba",
  "BR": "Brazil",
  "BS": "Bahamas",
  "BT": "Bhutan",
  "BV": "Bouvet Island",
  "BW": "Botswana",
  "BY": "Belarus",
  "BZ": "Belize",
  "CA": "Canada",
  "CC": "Cocos (Keeling) Islands",
  "CD": "DR Congo",
  "CF": "Central African Republic",
  "CG": "Republic of the Congo",
  "CH": "Switzerland",
  "CI": "Ivory Coast",
  "CK": "Cook Islands",
  "CL": "Chile",
  "CM": "Cameroon",
  "CN": "China",
  "CO": "Colombia",
  "CR": "Costa Rica",
  "CU": "Cuba",
  "CV": "Cabo Verde",
  "CW": "Curaçao",
  "CX": "Christmas Island",
  "CY": "Cyprus",
  "CZ": "Czechia",
  "DE": "Germany",
  "DJ": "Djibouti",
  "DK": "Denmark",
  "DM": "Dominica",
  "DO": "Dominican Republic",
  "DZ": "Algeria",
  "EC": "Ecuador",
  "EE": "Estonia",
  "EG": "Egypt",
  "EH": "Western Sahara",
  "ER": "Eritrea",
  "ES": "Spain",
  "ET": "Ethiopia",
  "FI": "Finland",
  "FJ": "Fiji",
  "FK": "Falkland Islands (Malvinas)",
  "FM": "Micronesia",
  "FO": "Faroe Islands",
  "FR": "France",
  "GA": "Gabon",
  "GB": "United Kingdom",
  "GD": "Grenada",
  "GE": "Georgia",
  "GF": "French Guiana",
  "GG": "Guernsey",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GL": "Greenland",
  "GM": "Gambia",
  "GN": "Guinea",
  "GP": "Guadeloupe",
  "GQ": "Equatorial Guinea",
  "GR": "Greece",
  "GS": "South Georgia and the South Sandwich Islands",
  "GT": "Guatemala",
  "GU": "Guam",
  "GW": "Guinea-Bissau",
  "GY": "Guyana",
  "HK": "Hong Kong",
  "HM": "Heard Island and McDonald Islands",
  "HN": "Honduras",
  "HR": "Croatia",
  "HT": "Haiti",
  "HU": "Hungary",
  "ID": "Indonesia",
  "IE": "Ireland",
  "IL": "Israel",
  "IM": "Isle of Man",
  "IN": "India",
  "IO": "British Indian Ocean Territory",
  "IQ": "Iraq",
  "IR": "Iran",
  "IS": "Iceland",
  "IT": "Italy",
  "JE": "Jersey",
  "JM": "Jamaica",
  "JO": "Jordan",
  "JP": "Japan",
  "KE": "Kenya",
  "KG": "Kyrgyzstan",
  "KH": "Cambodia",
  "KI": "Kiribati",
  "KM": "Comoros",
  "KN": "Saint Kitts and Nevis",
  "KP": "North Korea",
  "KR": "South Korea",
  "KW": "Kuwait",
  "KY": "Cayman Islands",
  "KZ": "Kazakhstan",
  "LA": "Laos",
  "LB": "Lebanon",
  "LC": "Saint Lucia",
  "LI": "Liechtenstein",
  "LK": "Sri Lanka",
  "LR": "Liberia",
  "LS": "Lesotho",
  "LT": "Lithuania",
  "LU": "Luxembourg",
  "LV": "Latvia",
  "LY": "Libya",
  "MA": "Morocco",
  "MC": "Monaco",
  "MD": "Moldova",
  "ME": "Montenegro",
  "MF": "Saint Martin (French part)",
  "MG": "Madagascar",
  "MH": "Marshall Islands",
  "MK": "North Macedonia",
  "ML": "Mali",
  "MM": "Myanmar",
  "MN": "Mongolia",
  "MO": "Macao",
  "MP": "Northern Mariana Islands",
  "MQ": "Martinique",
  "MR": "Mauritania",
  "MS": "Montserrat",
  "MT": "Malta",
  "MU": "Mauritius",
  "MV": "Maldives",
  "MW": "Malawi",
  "MX": "Mexico",
  "MY": "Malaysia",
  "MZ": "Mozambique",
  "NA": "Namibia",
  "NC": "New Caledonia",
  "NE": "Niger",
  "NF": "Norfolk Island",
  "NG": "Nigeria",
  "NI": "Nicaragua",
  "NL": "Netherlands",
  "NO": "Norway",
  "NP": "Nepal",
  "NR": "Nauru",
  "NU": "Niue",
  "NZ": "New Zealand",
  "OM": "Oman",
  "PA": "Panama",
  "PE": "Peru",
  "PF": "French Polynesia",
  "PG": "Papua New Guinea",
  "PH": "Philippines",
  "PK": "Pakistan",
  "PL": "Poland",
  "PM": "Saint Pierre and Miquelon",
  "PN": "Pitcairn",
  "PR": "Puerto Rico",
  "PS": "Palestine",
  "PT": "Portugal",
  "PW": "Palau",
  "PY": "Paraguay",
  "QA": "Qatar",
  "RE": "Réunion",
  "RO": "Romania",
  "RS": "Serbia",
  "RU": "Russia",
  "RW": "Rwanda",
  "SA": "Saudi Arabia",
  "SB": "Solomon Islands",
  "SC": "Seychelles",
  "SD": "Sudan",
  "SE": "Sweden",
  "SG": "Singapore",
  "SH": "Saint Helena, Ascension and Tristan da Cunha",
  "SI": "Slovenia",
  "SJ": "Svalbard and Jan Mayen",
  "SK": "Slovakia",
  "SL": "Sierra Leone",
  "SM": "San Marino",
  "SN": "Senegal",
  "SO": "Somalia",
  "SR": "Suriname",
  "SS": "South Sudan",
  "ST": "Sao Tome and Principe",
  "SV": "El Salvador",
  "SX": "Sint Maarten (Dutch part)",
  "SY": "Syria",
  "SZ": "Eswatini",
  "TC": "Turks and Caicos Islands",
  "TD": "Chad",
  "TF": "French Southern Territories",
  "TG": "Togo",
  "TH": "Thailand",
  "TJ": "Tajikistan",
  "TK": "Tokelau",
  "TL": "Timor-Leste",
  "TM": "Turkmenistan",
  "TN": "Tunisia",
  "TO": "Tonga",
  "TR": "Türkiye",
  "TT": "Trinidad and Tobago",
  "TV": "Tuvalu",
  "TW": "Taiwan",
  "TZ": "Tanzania",
  "UA": "Ukraine",
  "UG": "Uganda",
  "UM": "United States Minor Outlying Islands",
  "US": "United States",
  "UY": "Uruguay",
  "UZ": "Uzbekistan",
  "VA": "Vatican City",
  "VC": "Saint Vincent and the Grenadines",
  "VE": "Venezuela",
  "VG": "British Virgin Islands",
  "VI": "U.S. Virgin Islands",
  "VN": "Vietnam",
  "VU": "Vanuatu",
  "WF": "Wallis and Futuna",
  "WS": "Samoa",
  "YE": "Yemen",
  "YT": "Mayotte",
  "ZA": "South Africa",
  "ZM": "Zambia",
  "ZW": "Zimbabwe"
};

// Levenshtein distance, used only as a last-resort fallback to catch
// small typos ("Grmany", "Austrailia") against the full country name
// list above. Kept tiny and dependency-free.
function levenshtein(a, b) {
  const m = a.length;
  const n = b.length;
  if (m === 0) return n;
  if (n === 0) return m;

  const prev = new Array(n + 1);
  const curr = new Array(n + 1);

  for (let j = 0; j <= n; j += 1) prev[j] = j;

  for (let i = 1; i <= m; i += 1) {
    curr[0] = i;
    for (let j = 1; j <= n; j += 1) {
      const cost = a[i - 1] === b[j - 1] ? 0 : 1;
      curr[j] = Math.min(
        prev[j] + 1,
        curr[j - 1] + 1,
        prev[j - 1] + cost,
      );
    }
    for (let j = 0; j <= n; j += 1) prev[j] = curr[j];
  }

  return prev[n];
}

const ALL_ALIAS_KEYS = Object.keys(COUNTRY_ALIASES);

function fuzzyMatchAlpha2(input) {
  let best = null;
  let bestDistance = Infinity;

  ALL_ALIAS_KEYS.forEach((key) => {
    if (key.length <= 3) return;

    const distance = levenshtein(input, key);
    const threshold = key.length <= 5 ? 1 : 2;

    if (distance <= threshold && distance < bestDistance) {
      bestDistance = distance;
      best = COUNTRY_ALIASES[key];
    }
  });

  return best;
}

function resolveCountry(rawCountry) {
  const trimmed = String(rawCountry || "").trim();

  if (!trimmed) return null;

  const key = trimmed.toLowerCase();

  const directCode = COUNTRY_ALIASES[key] || fuzzyMatchAlpha2(key);

  if (!directCode) return null;

  return { code: directCode, name: ALPHA2_TO_NAME[directCode] || trimmed };
}

function ClinicalSitesMap({ sites = [] }: any) {
  const { chartData, unresolved } = useMemo(() => {
    const totals: Record<string, any> = {};;
    const unmatched = new Set<any>();

    sites.forEach((site) => {
      const rawCountry = site.country;
      const resolved = resolveCountry(rawCountry);

      if (!resolved) {
        const trimmed = String(rawCountry || "").trim();
        if (trimmed) unmatched.add(trimmed);
        return;
      }

      totals[resolved.code] =
        (totals[resolved.code] || 0) + Number(site.enrolled || 0);
    });

    const data = [["Country", "Enrolled"]];

    Object.entries(totals).forEach(([code, enrolled]) => {
      data.push([code, enrolled]);
    });

    return { chartData: data, unresolved: Array.from(unmatched) };
  }, [sites]);

  const options = {
    colorAxis: {
      colors: ["#dbeafe", "#2563eb", "#0f2f6b"],
    },
    backgroundColor: "#ffffff",
    datalessRegionColor: "#eeeeee",
    defaultColor: "#eeeeee",
    legend: {
      textStyle: {
        fontSize: 12,
      },
    },
    tooltip: {
      textStyle: {
        fontSize: 13,
      },
    },
  };

  if (chartData.length === 1) {
    return (
      <div
        style={{
          height: "26.25rem",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          color: "#666",
        }}>

        No countries available.
      </div>
    );
  }

  return (
    <div>
      <Chart
        chartType="GeoChart"
        width="100%"
        height="450px"
        data={chartData}
        options={options}
      />

      {unresolved.length > 0 && (
        <p style={{ fontSize: "0.75rem", color: "#888", marginTop: "0.5rem" }}>
          Could not place on the map: {unresolved.join(", ")}. Check the
          spelling of the country field for these sites.
        </p>
      )}
    </div>
  );
}

export default ClinicalSitesMap;