const DOCUMENT_TYPES = Object.freeze({
  PROTOCOL: "Protocol",
  CONSENT_FORM: "Consent Form",
  REGULATORY: "Regulatory",
  ETHICS: "Ethics",
  TRAINING: "Training",
  CV: "CV",
  DELEGATION_LOG: "Delegation Log",
  COMMUNICATION: "Communication",
  MONITORING: "Monitoring",
  SAFETY: "Safety",
  LABORATORY: "Laboratory",
  FINANCE: "Finance",
  LEGAL: "Legal",
  SOP: "SOP",
  SITE_INITIATION: "Site Initiation",
  RECRUITMENT: "Recruitment",
  RANDOMIZATION: "Randomization",
  DATA_MANAGEMENT: "Data Management",
  SUPPLIES: "Supplies",
  ARCHIVING: "Archiving",
  INVESTIGATIONAL_PRODUCT: "Investigational Product",
  OTHER: "Other",
});

/**
 * Document type dropdown options
 */
export const DOCUMENT_TYPE_OPTIONS = [
  DOCUMENT_TYPES.PROTOCOL,
  DOCUMENT_TYPES.CONSENT_FORM,
  DOCUMENT_TYPES.REGULATORY,
  DOCUMENT_TYPES.ETHICS,
  DOCUMENT_TYPES.TRAINING,
  DOCUMENT_TYPES.CV,
  DOCUMENT_TYPES.DELEGATION_LOG,
  DOCUMENT_TYPES.COMMUNICATION,
  DOCUMENT_TYPES.MONITORING,
  DOCUMENT_TYPES.SAFETY,
  DOCUMENT_TYPES.LABORATORY,
  DOCUMENT_TYPES.FINANCE,
  DOCUMENT_TYPES.LEGAL,
  DOCUMENT_TYPES.SOP,
  DOCUMENT_TYPES.SITE_INITIATION,
  DOCUMENT_TYPES.RECRUITMENT,
  DOCUMENT_TYPES.RANDOMIZATION,
  DOCUMENT_TYPES.DATA_MANAGEMENT,
  DOCUMENT_TYPES.SUPPLIES,
  DOCUMENT_TYPES.ARCHIVING,
  DOCUMENT_TYPES.INVESTIGATIONAL_PRODUCT,
  DOCUMENT_TYPES.OTHER,
];

/**
 * Clinical / Study document types
 */
export const STUDY_DOCUMENT_TYPES = [
  DOCUMENT_TYPES.PROTOCOL,
  DOCUMENT_TYPES.CONSENT_FORM,
  DOCUMENT_TYPES.ETHICS,
  DOCUMENT_TYPES.REGULATORY,
  DOCUMENT_TYPES.SITE_INITIATION,
];

/**
 * Site document types
 */
export const SITE_DOCUMENT_TYPES = [
  DOCUMENT_TYPES.CV,
  DOCUMENT_TYPES.DELEGATION_LOG,
  DOCUMENT_TYPES.TRAINING,
  DOCUMENT_TYPES.MONITORING,
];

/**
 * Operational document types
 */
export const OPERATIONAL_DOCUMENT_TYPES = [
  DOCUMENT_TYPES.DATA_MANAGEMENT,
  DOCUMENT_TYPES.SAFETY,
  DOCUMENT_TYPES.LABORATORY,
  DOCUMENT_TYPES.FINANCE,
  DOCUMENT_TYPES.LEGAL,
  DOCUMENT_TYPES.SUPPLIES,
  DOCUMENT_TYPES.ARCHIVING,
];

/**
 * Returns whether a document type exists.
 */
export const isValidDocumentType = (type) =>
  DOCUMENT_TYPE_OPTIONS.includes(type);

export default DOCUMENT_TYPES;