const DOCUMENT_STATUS = Object.freeze({
  DRAFT: "Draft",

  PENDING: "Pending",

  UNDER_REVIEW: "Under Review",

  UNDER_APPROVAL: "Under Approval",

  APPROVED: "Approved",

  REJECTED: "Rejected",

  SUPERSEDED: "Superseded",

  EXPIRED: "Expired",

  ARCHIVED: "Archived",

  MISSING: "Missing",
});

/**
 * Status dropdown options
 */
export const DOCUMENT_STATUS_OPTIONS = [
  DOCUMENT_STATUS.DRAFT,
  DOCUMENT_STATUS.PENDING,
  DOCUMENT_STATUS.UNDER_REVIEW,
  DOCUMENT_STATUS.UNDER_APPROVAL,
  DOCUMENT_STATUS.APPROVED,
  DOCUMENT_STATUS.REJECTED,
  DOCUMENT_STATUS.SUPERSEDED,
  DOCUMENT_STATUS.EXPIRED,
  DOCUMENT_STATUS.ARCHIVED,
  DOCUMENT_STATUS.MISSING,
];

/**
 * Editable document statuses.
 */
export const EDITABLE_DOCUMENT_STATUSES = [
  DOCUMENT_STATUS.DRAFT,
  DOCUMENT_STATUS.PENDING,
  DOCUMENT_STATUS.REJECTED,
];

/**
 * Final document statuses.
 */
export const FINAL_DOCUMENT_STATUSES = [
  DOCUMENT_STATUS.APPROVED,
  DOCUMENT_STATUS.ARCHIVED,
  DOCUMENT_STATUS.SUPERSEDED,
  DOCUMENT_STATUS.EXPIRED,
];

/**
 * Active document statuses.
 */
export const ACTIVE_DOCUMENT_STATUSES = [
  DOCUMENT_STATUS.DRAFT,
  DOCUMENT_STATUS.PENDING,
  DOCUMENT_STATUS.UNDER_REVIEW,
  DOCUMENT_STATUS.UNDER_APPROVAL,
  DOCUMENT_STATUS.APPROVED,
];

/**
 * Dashboard statuses.
 */
export const DASHBOARD_DOCUMENT_STATUSES = [
  DOCUMENT_STATUS.APPROVED,
  DOCUMENT_STATUS.PENDING,
  DOCUMENT_STATUS.UNDER_REVIEW,
  DOCUMENT_STATUS.UNDER_APPROVAL,
  DOCUMENT_STATUS.EXPIRED,
  DOCUMENT_STATUS.MISSING,
];

export default DOCUMENT_STATUS;