"""initial schema parity

Revision ID: 70f65d974cc7
Revises: 
Create Date: 2026-09-03 22:20:38.023567+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70f65d974cc7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_plantier',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_studies', sa.Integer(), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('storage_limit_gb', sa.Integer(), nullable=True),
    sa.Column('features', sa.Text(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('single_default_plan_tier', 'billing_plantier', ['is_default'], unique=True, sqlite_where=sa.text('is_default'))
    op.create_table('django_session',
    sa.Column('session_key', sa.String(length=40), nullable=False),
    sa.Column('session_data', sa.Text(), nullable=False),
    sa.Column('expire_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('session_key')
    )
    op.create_table('licensing_referralprogramsettings',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('referrer_bonus_enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizations_organization',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions_plan',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_studies', sa.Integer(), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('storage_limit_gb', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('billing_subscription',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('auto_renewal', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('max_studies_override', sa.Integer(), nullable=True),
    sa.Column('max_users_override', sa.Integer(), nullable=True),
    sa.Column('storage_limit_gb_override', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('plan_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations_organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['billing_plantier.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id')
    )
    op.create_index(op.f('ix_billing_subscription_plan_id'), 'billing_subscription', ['plan_id'], unique=False)
    op.create_table('organizations_role',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('organization_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations_organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_role_organization_id'), 'organizations_role', ['organization_id'], unique=False)
    op.create_table('subscriptions_subscription',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('auto_renewal', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('plan_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations_organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['subscriptions_plan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id')
    )
    op.create_index(op.f('ix_subscriptions_subscription_plan_id'), 'subscriptions_subscription', ['plan_id'], unique=False)
    op.create_table('accounts_user',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=False),
    sa.Column('last_name', sa.String(length=150), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('date_joined', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('profile_photo', sa.String(length=100), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('session_token', sa.String(length=32), nullable=False),
    sa.Column('last_activity', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=False),
    sa.Column('organization_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('role_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations_organization.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['organizations_role.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_accounts_user_organization_id'), 'accounts_user', ['organization_id'], unique=False)
    op.create_index(op.f('ix_accounts_user_role_id'), 'accounts_user', ['role_id'], unique=False)
    op.create_table('billing_paymenttransaction',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('gateway', sa.String(length=20), nullable=False),
    sa.Column('gateway_order_id', sa.String(length=64), nullable=True),
    sa.Column('gateway_payment_id', sa.String(length=64), nullable=True),
    sa.Column('gateway_signature', sa.String(length=512), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('raw_webhook_payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('subscription_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('plan_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['billing_plantier.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['billing_subscription.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gateway_order_id')
    )
    op.create_index(op.f('ix_billing_paymenttransaction_gateway_payment_id'), 'billing_paymenttransaction', ['gateway_payment_id'], unique=False)
    op.create_index(op.f('ix_billing_paymenttransaction_plan_id'), 'billing_paymenttransaction', ['plan_id'], unique=False)
    op.create_index(op.f('ix_billing_paymenttransaction_subscription_id'), 'billing_paymenttransaction', ['subscription_id'], unique=False)
    op.create_table('billing_subscriptionevent',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('metadata', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('subscription_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['billing_subscription.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_subscriptionevent_event_type'), 'billing_subscriptionevent', ['event_type'], unique=False)
    op.create_index(op.f('ix_billing_subscriptionevent_subscription_id'), 'billing_subscriptionevent', ['subscription_id'], unique=False)
    op.create_table('accounts_auditlog',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=39), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('signature_token', sa.String(length=32), nullable=False),
    sa.Column('signature_meaning', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['accounts_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signature_token')
    )
    op.create_index(op.f('ix_accounts_auditlog_user_id'), 'accounts_auditlog', ['user_id'], unique=False)
    op.create_table('accounts_loginotp',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('otp_code', sa.String(length=6), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['accounts_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_loginotp_user_id'), 'accounts_loginotp', ['user_id'], unique=False)
    op.create_table('accounts_passwordresettoken',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('otp_code', sa.String(length=6), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['accounts_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_accounts_passwordresettoken_user_id'), 'accounts_passwordresettoken', ['user_id'], unique=False)
    op.create_table('accounts_uploadeddocument',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('document_number', sa.Integer(), nullable=True),
    sa.Column('file', sa.String(length=100), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('uploaded_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations_organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['accounts_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_number')
    )
    op.create_index(op.f('ix_accounts_uploadeddocument_organization_id'), 'accounts_uploadeddocument', ['organization_id'], unique=False)
    op.create_index(op.f('ix_accounts_uploadeddocument_uploaded_by_id'), 'accounts_uploadeddocument', ['uploaded_by_id'], unique=False)
    op.create_table('accounts_uploadform',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('form_type', sa.String(length=20), nullable=False),
    sa.Column('file', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['accounts_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_uploadform_user_id'), 'accounts_uploadform', ['user_id'], unique=False)
    op.create_table('accounts_uploadlog',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['accounts_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_uploadlog_user_id'), 'accounts_uploadlog', ['user_id'], unique=False)
    op.create_table('licensing_referralcode',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('redemption_count', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['accounts_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('monitoring_monitoringaccessrequest',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('requester_role_label', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decision_note', sa.String(length=255), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('requested_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('approved_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('site_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['accounts_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['accounts_user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['organizations_organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_monitoringaccessrequest_approved_by_id'), 'monitoring_monitoringaccessrequest', ['approved_by_id'], unique=False)
    op.create_index(op.f('ix_monitoring_monitoringaccessrequest_requested_by_id'), 'monitoring_monitoringaccessrequest', ['requested_by_id'], unique=False)
    op.create_index(op.f('ix_monitoring_monitoringaccessrequest_site_id'), 'monitoring_monitoringaccessrequest', ['site_id'], unique=False)
    op.create_table('licensing_referralusage',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('redeemed_at', sa.DateTime(), nullable=False),
    sa.Column('referee_days_granted', sa.Integer(), nullable=False),
    sa.Column('referrer_days_granted', sa.Integer(), nullable=False),
    sa.Column('referee_license_start_date', sa.DateTime(), nullable=False),
    sa.Column('referee_license_end_date', sa.DateTime(), nullable=False),
    sa.Column('referee_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('referrer_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('code_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['code_id'], ['licensing_referralcode.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referee_id'], ['accounts_user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referrer_id'], ['accounts_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referee_id')
    )
    op.create_index(op.f('ix_licensing_referralusage_code_id'), 'licensing_referralusage', ['code_id'], unique=False)
    op.create_index(op.f('ix_licensing_referralusage_referrer_id'), 'licensing_referralusage', ['referrer_id'], unique=False)
    op.create_table('licensing_licenseentitlement',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('subscription_end_date', sa.DateTime(), nullable=True),
    sa.Column('referral_extension_end_date', sa.DateTime(), nullable=True),
    sa.Column('referral_extension_days_total', sa.Integer(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('referral_extension_source_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.ForeignKeyConstraint(['referral_extension_source_id'], ['licensing_referralusage.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['accounts_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_licensing_licenseentitlement_referral_extension_source_id'), 'licensing_licenseentitlement', ['referral_extension_source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_licensing_licenseentitlement_referral_extension_source_id'), table_name='licensing_licenseentitlement')
    op.drop_table('licensing_licenseentitlement')
    op.drop_index(op.f('ix_licensing_referralusage_referrer_id'), table_name='licensing_referralusage')
    op.drop_index(op.f('ix_licensing_referralusage_code_id'), table_name='licensing_referralusage')
    op.drop_table('licensing_referralusage')
    op.drop_index(op.f('ix_monitoring_monitoringaccessrequest_site_id'), table_name='monitoring_monitoringaccessrequest')
    op.drop_index(op.f('ix_monitoring_monitoringaccessrequest_requested_by_id'), table_name='monitoring_monitoringaccessrequest')
    op.drop_index(op.f('ix_monitoring_monitoringaccessrequest_approved_by_id'), table_name='monitoring_monitoringaccessrequest')
    op.drop_table('monitoring_monitoringaccessrequest')
    op.drop_table('licensing_referralcode')
    op.drop_index(op.f('ix_accounts_uploadlog_user_id'), table_name='accounts_uploadlog')
    op.drop_table('accounts_uploadlog')
    op.drop_index(op.f('ix_accounts_uploadform_user_id'), table_name='accounts_uploadform')
    op.drop_table('accounts_uploadform')
    op.drop_index(op.f('ix_accounts_uploadeddocument_uploaded_by_id'), table_name='accounts_uploadeddocument')
    op.drop_index(op.f('ix_accounts_uploadeddocument_organization_id'), table_name='accounts_uploadeddocument')
    op.drop_table('accounts_uploadeddocument')
    op.drop_index(op.f('ix_accounts_passwordresettoken_user_id'), table_name='accounts_passwordresettoken')
    op.drop_table('accounts_passwordresettoken')
    op.drop_index(op.f('ix_accounts_loginotp_user_id'), table_name='accounts_loginotp')
    op.drop_table('accounts_loginotp')
    op.drop_index(op.f('ix_accounts_auditlog_user_id'), table_name='accounts_auditlog')
    op.drop_table('accounts_auditlog')
    op.drop_index(op.f('ix_billing_subscriptionevent_subscription_id'), table_name='billing_subscriptionevent')
    op.drop_index(op.f('ix_billing_subscriptionevent_event_type'), table_name='billing_subscriptionevent')
    op.drop_table('billing_subscriptionevent')
    op.drop_index(op.f('ix_billing_paymenttransaction_subscription_id'), table_name='billing_paymenttransaction')
    op.drop_index(op.f('ix_billing_paymenttransaction_plan_id'), table_name='billing_paymenttransaction')
    op.drop_index(op.f('ix_billing_paymenttransaction_gateway_payment_id'), table_name='billing_paymenttransaction')
    op.drop_table('billing_paymenttransaction')
    op.drop_index(op.f('ix_accounts_user_role_id'), table_name='accounts_user')
    op.drop_index(op.f('ix_accounts_user_organization_id'), table_name='accounts_user')
    op.drop_table('accounts_user')
    op.drop_index(op.f('ix_subscriptions_subscription_plan_id'), table_name='subscriptions_subscription')
    op.drop_table('subscriptions_subscription')
    op.drop_index(op.f('ix_organizations_role_organization_id'), table_name='organizations_role')
    op.drop_table('organizations_role')
    op.drop_index(op.f('ix_billing_subscription_plan_id'), table_name='billing_subscription')
    op.drop_table('billing_subscription')
    op.drop_table('subscriptions_plan')
    op.drop_table('organizations_organization')
    op.drop_table('licensing_referralprogramsettings')
    op.drop_table('django_session')
    op.drop_index('single_default_plan_tier', table_name='billing_plantier', sqlite_where=sa.text('is_default'))
    op.drop_table('billing_plantier')
    # ### end Alembic commands ###
